//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace camera.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class carpark
    {
        public carpark()
        {
            this.parkings = new HashSet<parking>();
        }
    
        public int CarparkID { get; set; }
        public string CarparkName { get; set; }
        public string GPSLocation { get; set; }
        public int Spaces { get; set; }
        public int RateID { get; set; }
        public int CarparkProviderID { get; set; }
    
        public virtual carparkprovider carparkprovider { get; set; }
        public virtual rate rate { get; set; }
        public virtual ICollection<parking> parkings { get; set; }
    }
}
