//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace camera.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class carparkprovider
    {
        public carparkprovider()
        {
            this.carparks = new HashSet<carpark>();
        }
    
        public int CarparkProviderID { get; set; }
        public string ProviderName { get; set; }
        public string ActiveAccountNum { get; set; }
    
        public virtual ICollection<carpark> carparks { get; set; }
    }
}
