//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace camera.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class customeracount
    {
        public int CustomerAccountID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> ParkingID { get; set; }
        public string TransactionType { get; set; }
        public double TransactionAmount { get; set; }
        public double CurrentBalance { get; set; }
        public System.DateTime TransactionDate { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual parking parking { get; set; }
    }
}
