//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace camera.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class parking
    {
        public parking()
        {
            this.customeraccounts = new HashSet<customeraccount>();
        }
    
        public int ParkingID { get; set; }
        public int CustomerID { get; set; }
        public int CarparkID { get; set; }
        public System.DateTime TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public Nullable<double> Cost { get; set; }
    
        public virtual carpark carpark { get; set; }
        public virtual ICollection<customeraccount> customeraccounts { get; set; }
    }
}
