//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace camera.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ratetype
    {
        public ratetype()
        {
            this.rates = new HashSet<rate>();
        }
    
        public int RateTypeID { get; set; }
        public string RateType1 { get; set; }
    
        public virtual ICollection<rate> rates { get; set; }
    }
}
