//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace camera.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rate
    {
        public rate()
        {
            this.carparks = new HashSet<carpark>();
        }
    
        public int RateID { get; set; }
        public int RateTypeID { get; set; }
        public double Rate1 { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
    
        public virtual ICollection<carpark> carparks { get; set; }
        public virtual ratetype ratetype { get; set; }
    }
}
