//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace camera.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tls_dbEntities : DbContext
    {
        public tls_dbEntities()
            : base("name=tls_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<carparkprovider> carparkproviders { get; set; }
        public virtual DbSet<carpark> carparks { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customeracount> customeracounts { get; set; }
        public virtual DbSet<parking> parkings { get; set; }
        public virtual DbSet<rate> rates { get; set; }
        public virtual DbSet<ratetype> ratetypes { get; set; }
        public virtual DbSet<vehicle> vehicles { get; set; }
    }
}
