//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace camera.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        public vehicle()
        {
            this.customers = new HashSet<customer>();
        }
    
        public int VehicleID { get; set; }
        public string VehicleRegNum { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
    
        public virtual ICollection<customer> customers { get; set; }
    }
}
